project:
  type: book
  output-dir: docs

book:
  title: "Mastering Health Data Science in R"
  author: "Alice Paul"
  #image: images/logo.png 
  sidebar:
    search: true
    #logo: images/logo.png
  favicon: fav.png
  date: "11/21/2023"
  date-format: "YYYY"
  search: true
  downloads: [pdf]
  repo-url: https://github.com/alicepaul/health-data-science-in-r 
  chapters:
  - index.qmd
  - part: Introduction to R
    chapters:
      - book/1_intro_to_r.qmd
      - book/2_data_structures.qmd
      - book/3_data_files.qmd
  - part: Exploratory Analysis
    chapters:
      - book/4_exploratory_analysis.qmd
      - book/5_data_transformations_summaries.qmd
      - book/6_merging_data.qmd
      - book/7_visualization_ggplot.qmd
  - part: Distributions and Hypothesis Testing
    chapters:
    - book/8_distributions.qmd
    - book/9_hypothesis_tests.qmd
  - part: Regression
    chapters:
      - book/10_linear_regression.qmd
      - book/11_logistic_regression.qmd
  - part: Extra Topics
    chapters:
      - book/12_rmarkdown_reports.qmd
      - book/13_expanding_r_skills.qmd

bibliography: references.bib

format:
  html:
    theme: [cosmos]
    fontsize: 0.85em
    linkcolor: orangered
    fontcolor: dimgrey
    author-meta: Alice Paul
  pdf:
    documentclass: scrreprt

knitr:
  opts_chunk:
    comment: "#>"
    collapse: TRUE
    cache: TRUE
    width: 72
    tidy.opts: list(width.cutoff=72, tidy=TRUE)
    out.width: 70%
    fig.align: 'center'
    fig.width: 6
    fig.height: 3.708  # width * 1 / phi
    fig.show: hold
    R.options:
      digits: 3
      width: 72
      formatR.indent: 2
      dplyr.summarise.inform: FALSE
      dplyr.print_min: 5 
      dplyr.print_max: 5
      ggrepel.max.overlaps: 100

editor: visual

