project:
  type: book
  output-dir: docs

execute:
  cache: false

book:
  title: "Mastering Health Data Science Using R"
  author: "Alice Paul"
  sidebar:
    search: true
  favicon: images/fav.png
  date: "11/21/2023"
  date-format: "YYYY"
  search: true
  downloads: [pdf]
  repo-url: https://github.com/alicepaul/health-data-science-using-r 
  chapters:
  - index.qmd
  - part: "Introduction to R"
    chapters:
    - book/intro_to_r.qmd
    - book/data_structures.qmd
    - book/data_files.qmd
  - part: Exploratory Analysis
    chapters:
    - book/exploratory_analysis.qmd
    - book/data_transformations_summaries.qmd
    - book/merging_data.qmd
    - book/visualization_ggplot.qmd
  - part: Distributions and Hypothesis Testing
    chapters:
    - book/distributions.qmd
    - book/hypothesis_tests.qmd
  - part: Regression
    chapters:
    - book/linear_regression.qmd
    - book/logistic_regression.qmd
  - part: Extra Topics
    chapters:
    - book/rmarkdown_reports.qmd
    - book/expanding_r_skills.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: [cosmos]
    fontsize: 0.85em
    linkcolor: orangered
    fontcolor: dimgrey
    author-meta: Alice Paul
  pdf:
    documentclass: krantz
    keep-tex: false
    include-in-header: latex/preamble.tex
    include-before-body: latex/before_body.tex
    include-after-body: latex/after_body.tex

knitr:
  opts_chunk:
    comment: "#>"
    collapse: TRUE
    message: FALSE
    code-overflow: wrap
    cache: FALSE
    out.width: 100%
    fig.align: 'center'
    fig.width: 6
    fig.show: hold
    size: 'small'
    R.options:
      digits: 3
      width: 72
      formatR.indent: 2
      dplyr.summarise.inform: FALSE
      dplyr.print_min: 5 
      dplyr.print_max: 5
      

editor: visual

