channels:
  - conda-forge
  - defaults
dependencies:
  - r-base=4.2.3
  - conda-forge::r-tidyverse=1.3.2
  - conda-forge::r-gt=0.9.0
  - conda-forge::r-ggally=2.1.2
  - conda-forge::r-patchwork=1.1.2
  - conda-forge::r-broom=1.0.5
  - conda-forge::r-proc=1.18.2
  - conda-forge::r-car=3.1
  - conda-forge::r-lmtest=0.9.40
  - conda-forge::r-mass=7.3
  - conda-forge::r-gtsummary=1.7.1
  - conda-forge::r-lubridate=1.9.2
  - conda-forge::r-kableextra=1.3.4
