channels:
  - conda-forge
  - defaults
dependencies:
  - r-base=4.1.1
  - conda-forge::r-tidyverse=1.3.1 
  - r-gt=0.9.0
  - conda-forge::r-ggally=2.1.2
  - conda-forge::ggcorrplot=0.1.4
  - conda-forge::patchwork=1.1.2
