channels:
  - conda-forge
  - defaults
dependencies:
  - r-base=4.1.1
  - conda-forge::r-tidyverse=1.3.1 
  - r-gt=0.9.0
  - conda-forge::r-ggally=2.1.2
  - conda-forge::r-ggcorrplot=0.1.4
  - conda-forge::r-patchwork=1.1.2
  - conda-forge::datasets=2.13.0
  - conda-forge::r-haven=2.5.2
  - conda-forge::r-broom=1.0.5
  - conda-forge::r-proc=1.18.2
