# Mastering Health Data Science Using R {.unnumbered}

This book serves as an interactive introduction to R for public health and health data science students. Topics include data structures in R, exploratory analysis, distributions, hypothesis testing, and regression analysis. The presentation assumes knowledge with the underlying methodology and focuses instead on how to use R to implement your analysis.

This book is written using Jupyter Book. You can download each chapter as a Jupyter notebook or pdf directly from the chapter page or download a corresponding R Markdown file from the [github repository](https://github.com/alicepaul/health-data-science-in-r). Alternatively, you can open each notebook using Binder to directly run the code you see in the text and to test out your solutions to the exercises included. If this is your first time learning R or you are unfamiliar with Jupyter notebooks or R Markdown, we encourage you to start with [Chapter 1: Intro to R, RStudio, and Jupyter](book/1_intro_to_r) to get a tour on how to use these tools. The github repository also contains a few [cheat sheets](https://github.com/alicepaul/health-data-science-in-r/tree/main/book/docs) including a pdf containing [all functions](https://github.com/alicepaul/health-data-science-in-r/blob/main/book/docs/functions_cheat_sheet.pdf) shown in this book.

This work is licensed under the Creative Commons Attribution 4.0 International [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/).

This book is written by [Alice Paul](https://alicepaul.github.io/) with the support of a [Data Science Institute Seed Grant](https://dsi.brown.edu/). Thanks to students Jialin Liu, Joanna Walsh, and Xinbei Yu for their help and feedback. Please contact Dr. Paul (alice_paul\@brown.edu) with questions, suggested edits, or feedback.
