install.packages("remotes")
remotes::install_version("tidyverse", version = "1.3.2")
remotes::install_version("gt", version = "0.9.0")
remotes::install_version("ggally", version = "2.1.2")
remotes::install_version("patchwork", version = "1.1.2")
remotes::install_version("broom", version = "1.0.5")
remotes::install_version("proc", version = "1.18.2")
remotes::install_version("car", version = "3.1")
remotes::install_version("gtsummary", version = "1.7.1")
remotes::install_version("kableExtra", version = "1.3.4")
remotes::install_github("joannamwalsh/HDSinRdata")