name: Build Notebook Container
on: 
  label:
    types:
      - created
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout files in repo
      uses: actions/checkout@main

    - name: update jupyter dependencies with repo2docker
      uses: machine-learning-apps/repo2docker-action@master
      with:
        DOCKER_USERNAME: xinbeiyu
        DOCKER_PASSWORD: dckr_pat_zjiM_fCi52p3S7FtPHZzLndp2Mg
        BINDER_CACHE: true
